server:
  port: 8080
  servlet:
    context-path: /lureclub
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    connection-timeout: 20000
    max-connections: 10000

spring:
  application:
    name: lure-club-points-system
  profiles:
    active: dev

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/lureclub_points?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:GU}
    password: ${DB_PASSWORD:Gfj123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # SQL初始化配置 - 修复：指向正确的文件
  sql:
    init:
      mode: never
#      data-locations: classpath:data.sql
#      continue-on-error: true
#      encoding: utf-8

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}

# JWT配置
jwt:
  secret: ${JWT_SECRET:lureclub2025secretkey_this_should_be_very_long_and_secure}
  expiration: ${JWT_EXPIRATION:86400000} # 24小时

# 文件上传路径配置
file:
  upload:
    path: ${FILE_UPLOAD_PATH:uploads}
    prize-images: ${PRIZE_IMAGES_PATH:prizes}

# 积分任务配置
points:
  task:
    enabled: ${POINTS_TASK_ENABLED:true}
    cron: ${POINTS_TASK_CRON:0 0 1 * * ?}  # 每天凌晨1点
  check:
    cron: ${POINTS_CHECK_CRON:0 0 * * * ?}  # 每小时检查

# CORS配置
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000,http://127.0.0.1:8080}

# Swagger配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: ${SWAGGER_UI_ENABLED:true}

# 日志配置
logging:
  level:
    com.lureclub: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_SQL_BIND:TRACE}
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/lureclub-points.log}
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,metrics}
      base-path: /actuator
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when_authorized}
  info:
    git:
      mode: full

# 应用信息配置
info:
  app:
    name: 雷霆路亚俱乐部积分管理系统
    description: 路亚钓鱼俱乐部的积分管理和奖励系统
    version: 1.0.0
    author: system

# 业务参数配置
business:
  points:
    max-daily-points: ${MAX_DAILY_POINTS:1000}
    max-deduct-points: ${MAX_DEDUCT_POINTS:10000}
    points-to-money-ratio: ${POINTS_TO_MONEY_RATIO:1}  # 1积分=1元
  file:
    max-size: ${FILE_MAX_SIZE:10485760}  # 10MB
    allowed-types: ${FILE_ALLOWED_TYPES:jpg,jpeg,png,gif,webp}
  ranking:
    max-display-count: ${RANKING_MAX_COUNT:100}

# 安全配置
security:
  password:
    min-length: 6
    max-length: 20
    require-special-char: false
  login:
    max-attempts: 5
    lock-duration: 300000  # 5分钟