# 开发环境配置
server:
  port: 8080

spring:
  # 数据库配置 - 开发环境
  datasource:
    url: jdbc:mysql://localhost:3306/lureclub_points_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # JPA配置 - 开发环境
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # SQL初始化配置
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

# 日志配置 - 开发环境
logging:
  level:
    com.lureclub: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 文件上传路径 - 开发环境
file:
  upload:
    path: D:/uploads/lureclub/