# 生产环境配置
server:
  port: 8080
  servlet:
    context-path: /

spring:
  # 数据库配置 - 请替换为你的实际数据库信息
  datasource:
    url: jdbc:mysql://119.45.122.98:3306/lureclub_points?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: lure_admin
    password: Gfj123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# 日志配置
logging:
  level:
    com.lureclub: INFO
    root: INFO
  file:
    name: /var/log/lureclub/application.log

# 文件上传路径 - 生产环境
file:
  upload:
    path: /opt/tomcat/webapps/uploads/lureclub
    prize-images: prizes

# JWT配置
jwt:
  secret: lureclub2025secretkey_production_change_this_to_very_long_secure_key
  expiration: 86400000

# 积分任务配置
points:
  task:
    enabled: true
    cron: "0 0 1 * * ?"
  check:
    cron: "0 0 * * * ?"